name: Py-test testing ğŸ‡

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Pulling the code ğŸ­ğŸ­
        uses: actions/checkout@v3

      - name: Setting up python ğŸ¤¸â€â™€ï¸ğŸ¤¸â€â™€ï¸
        uses: actions/setup-python@v4  
        with:
          python-version: "3.10"

      - name: Installing dependencies ğŸ˜ğŸ˜
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests ğŸƒâ€â™‚ï¸ğŸƒâ€â™€ï¸
        run: pytest -v          